version: "3.9"

services:
  api:
    build: ./api
    ports:
      - 3000:3000
    init: true
    restart: always
    dns:
      - 8.8.8.8
    networks:
      - test
  ui:
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - 4000:80
    environment:
      - PORT=81
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - test

networks:
  test:
    driver: bridge
    attachable: false
